# tasks/main.yml

- name: Generate docker-compose.yml from template
  template:
    src: docker-compose.yml.j2
    dest: "{{ playbook_dir }}/docker-compose.yml"

- name: Deploy the cluster using docker-compose
  command: /usr/local/bin/docker-compose up -d
  args:
    chdir: "{{ playbook_dir }}"
  environment:
    PATH: "/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
