- hosts: "{{ COMP }}"
  gather_facts: false
  vars_files:
    - vars/common.vars
  tasks:
    - name: Check Connectivity
      win_ping:

    - name: Print variable values
      debug:
        msg:
          - "App name is: {{ app_name }}"
          - "File name is: {{ file_name }}"
          - "Destination path is: {{ dest_path }}"

    - name: Validate file extension
      fail:
        msg: "The file '{{ file_name }}' must have a .txt extension. Job failed!"
      when: file_name is not regex(".*\\.txt$")

    - name: Debug upload command
      debug:
        msg: >
          curl -v -k -u {{ nexus_username }}:'{{ nexus_password }}'
          --upload-file "{{ apps[app_name].source_path }}\\{{ file_name }}"
          {{ dest_path }}

    - name: Upload file to Nexus
      win_shell: >
        curl.exe -v -k -u {{ nexus_username }}:'{{ nexus_password }}'
        --upload-file "{{ apps[app_name].source_path }}\\{{ file_name }}"
        {{ dest_path }}
      when: task == "upload"

      