- hosts: localhost
  gather_facts: false
  become: yes
  become_method: sudo
  become_user: root
  vars:
    dir: playbooks

  tasks:
    - name: Write file name
      shell: echo "{{ file_name }} {{ checksum }}" > "{{ jenkins_ws }}/{{ dir }}/release/release.txt"

    - name: Change file permission
      file:
        path: "{{ jenkins_ws }}/{{ dir }}/release/{{ item }}"
        mode: '0755'
      with_items:
        - release.txt
        - verify_checksum.sh

    - name: Read file from checksum
      shell: "cat {{ jenkins_ws }}/{{ dir }}/release/release.txt"
      register: nexus_checksum

    - name: Debug Nexus checksum
      debug:
        msg: "{{ nexus_checksum.stdout.splitlines() }}"

    - name: Read file from checksum
      shell: "cat {{ jenkins_ws }}/{{ dir }}/release/RELEASE_FILE.txt"
      register: git_checksum

    - name: Debug Git checksum
      debug:
        msg: "{{ git_checksum.stdout.splitlines() }}"

    - name: Execute script
      args:
        chdir: "{{ jenkins_ws }}/{{ dir }}/release/"
      command: 'sh verify_checksum.sh'
      async: 300
      poll: 10
      register: execscript

    - name: Display script output
      debug:
        msg: "{{ execscript.stdout | default('No output available').splitlines() }}"
